server:
  port: 8101 # 内嵌的 Tomcat 端口号。
  
spring:
  servlet:
    multipart:
      max-file-size: 1024MB # 单个文件大小
      max-request-size: 1024MB # 设置总上传的数据大小
      enabled: true #开启

thread:
  corePoolSize: 10
  maxPoolSize: 50

http:
   max-connection: 2000
   max-per-route: 100
   max-retry: 3
   connect-timeout: 20000
   read-timeout: 60000
   request-timeout: 20000

local:
   local-path: " "